version: '3.8'
services:
  irating:
#    image: challenge_application
    container_name: irating
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - "6379:6379"

  flower:
    container_name: flower
    build: .
    volumes:
      - ./:/usr/src/app
    command: celery $app $tasks flower
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq//
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    depends_on:
      - irating

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A iRating beat -l INFO
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq//
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq

volumes:
  irating_data:

