version: '3.8'
services:
  worker:
    container_name: worker
    build: .
    command: celery -A iRating worker -l INFO --concurrency 1
    env_file: iRating/.env
    volumes:
      - .:/usr/src/app
