# Generated by Django 4.0.4 on 2022-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_restaurant_alter_rating_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product_rate',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
