# Generated by Django 4.0.4 on 2022-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rating_product_rate_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
