# Generated by Django 4.0.4 on 2022-06-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_rating_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='restaurant',
        ),
    ]
